snapshot:
  url: https://raw.githubusercontent.com/commercialhaskell/stackage-snapshots/master/lts/22/39.yaml

packages:
- .


compiler: ghc-9.6.7
system-ghc: true
install-ghc: false


extra-lib-dirs:
  - /usr/lib/x86_64-linux-gnu
  - /lib/x86_64-linux-gnu
  - /home/jurydes/.local/lib

extra-include-dirs:
  - /usr/include
