name:                 perceptron
version:              0.1.0.0
visibility:           public
id:                   perceptron-0.1.0.0-inplace
key:                  perceptron-0.1.0.0-inplace
license:              BSD-3-Clause
synopsis:             Реализация алгоритма перцептрона — курсовой проект по ML
description:
    Перцептрон Розенблатта с тремя функциями активации (ADT).
    Поддерживает обучение, предсказание, оценку качества и
    сохранение/загрузку модели.

abi:                  inplace
exposed:              True
exposed-modules:      DataLoader Evaluation ModelSerializer Perceptron
import-dirs:
    /home/jurydes/mlp/perceptron/dist-newstyle/build/x86_64-linux/ghc-8.8.4/perceptron-0.1.0.0/build

library-dirs:
    /home/jurydes/mlp/perceptron/dist-newstyle/build/x86_64-linux/ghc-8.8.4/perceptron-0.1.0.0/build
    /home/jurydes/.local/lib /usr/lib/x86_64-linux-gnu
    /lib/x86_64-linux-gnu

dynamic-library-dirs:
    /home/jurydes/mlp/perceptron/dist-newstyle/build/x86_64-linux/ghc-8.8.4/perceptron-0.1.0.0/build
    /home/jurydes/.local/lib /usr/lib/x86_64-linux-gnu
    /lib/x86_64-linux-gnu

data-dir:             /home/jurydes/mlp/perceptron
hs-libraries:         HSperceptron-0.1.0.0-inplace
depends:
    base-4.13.0.0 directory-1.3.6.0
    hmatrix-0.20.2-55ac9d9a588cebfbd75d875447287cd5d395dadf7f39754dfffccb026e5dbe0b

haddock-interfaces:
    /home/jurydes/mlp/perceptron/dist-newstyle/build/x86_64-linux/ghc-8.8.4/perceptron-0.1.0.0/doc/html/perceptron/perceptron.haddock

haddock-html:
    /home/jurydes/mlp/perceptron/dist-newstyle/build/x86_64-linux/ghc-8.8.4/perceptron-0.1.0.0/doc/html/perceptron
