name:                 perceptron
version:              0.1.0.0
visibility:           public
id:                   perceptron-0.1.0.0-JyM3HxfKAugC6CUTZY4zeM
key:                  perceptron-0.1.0.0-JyM3HxfKAugC6CUTZY4zeM
license:              BSD-3-Clause
synopsis:             Реализация алгоритма перцептрона — курсовой проект по ML
description:
    Перцептрон Розенблатта с тремя функциями активации (ADT).
    Поддерживает обучение, предсказание, оценку качества и
    сохранение/загрузку модели.

abi:                  3a7b4e0c37f09cc08e21bf11f4018498
exposed:              True
exposed-modules:      DataLoader Evaluation ModelSerializer Perceptron
import-dirs:
    /home/jurydes/mlp/perceptron/.stack-work/install/x86_64-linux/6c24fa9160771461153267ed24106c91cc8535c5c0caf2e03038088a2cf6304b/9.6.7/lib/x86_64-linux-ghc-9.6.7/perceptron-0.1.0.0-JyM3HxfKAugC6CUTZY4zeM

library-dirs:
    /home/jurydes/mlp/perceptron/.stack-work/install/x86_64-linux/6c24fa9160771461153267ed24106c91cc8535c5c0caf2e03038088a2cf6304b/9.6.7/lib/x86_64-linux-ghc-9.6.7/perceptron-0.1.0.0-JyM3HxfKAugC6CUTZY4zeM
    /usr/lib/x86_64-linux-gnu /lib/x86_64-linux-gnu
    /home/jurydes/.local/lib

library-dirs-static:
    /home/jurydes/mlp/perceptron/.stack-work/install/x86_64-linux/6c24fa9160771461153267ed24106c91cc8535c5c0caf2e03038088a2cf6304b/9.6.7/lib/x86_64-linux-ghc-9.6.7/perceptron-0.1.0.0-JyM3HxfKAugC6CUTZY4zeM
    /usr/lib/x86_64-linux-gnu /lib/x86_64-linux-gnu
    /home/jurydes/.local/lib

dynamic-library-dirs:
    /home/jurydes/mlp/perceptron/.stack-work/install/x86_64-linux/6c24fa9160771461153267ed24106c91cc8535c5c0caf2e03038088a2cf6304b/9.6.7/lib/x86_64-linux-ghc-9.6.7
    /usr/lib/x86_64-linux-gnu /lib/x86_64-linux-gnu
    /home/jurydes/.local/lib

data-dir:
    /home/jurydes/mlp/perceptron/.stack-work/install/x86_64-linux/6c24fa9160771461153267ed24106c91cc8535c5c0caf2e03038088a2cf6304b/9.6.7/share/x86_64-linux-ghc-9.6.7/perceptron-0.1.0.0

hs-libraries:         HSperceptron-0.1.0.0-JyM3HxfKAugC6CUTZY4zeM
include-dirs:         /usr/include
depends:
    base-4.18.3.0 directory-1.3.8.5
    hmatrix-0.20.2-pP7f0SA5bI5iH5zxVXMGE

haddock-interfaces:
    /home/jurydes/mlp/perceptron/.stack-work/install/x86_64-linux/6c24fa9160771461153267ed24106c91cc8535c5c0caf2e03038088a2cf6304b/9.6.7/doc/perceptron-0.1.0.0/perceptron.haddock

haddock-html:
    /home/jurydes/mlp/perceptron/.stack-work/install/x86_64-linux/6c24fa9160771461153267ed24106c91cc8535c5c0caf2e03038088a2cf6304b/9.6.7/doc/perceptron-0.1.0.0
