name:                 perceptron
version:              0.1.0.0
visibility:           public
id:                   perceptron-0.1.0.0-inplace
key:                  perceptron-0.1.0.0-inplace
license:              BSD-3-Clause
synopsis:             Реализация алгоритма перцептрона — курсовой проект по ML
description:
    Перцептрон Розенблатта с тремя функциями активации (ADT).
    Поддерживает обучение, предсказание, оценку качества и
    сохранение/загрузку модели.

abi:                  inplace
exposed:              True
exposed-modules:      DataLoader Evaluation ModelSerializer Perceptron
import-dirs:
    /home/jurydes/mlp/perceptron/dist-newstyle/build/x86_64-linux/ghc-9.6.7/perceptron-0.1.0.0/build

library-dirs:
    /home/jurydes/mlp/perceptron/dist-newstyle/build/x86_64-linux/ghc-9.6.7/perceptron-0.1.0.0/build
    /home/jurydes/.local/lib /usr/lib/x86_64-linux-gnu
    /lib/x86_64-linux-gnu

library-dirs-static:
    /home/jurydes/mlp/perceptron/dist-newstyle/build/x86_64-linux/ghc-9.6.7/perceptron-0.1.0.0/build
    /home/jurydes/.local/lib /usr/lib/x86_64-linux-gnu
    /lib/x86_64-linux-gnu

dynamic-library-dirs:
    /home/jurydes/mlp/perceptron/dist-newstyle/build/x86_64-linux/ghc-9.6.7/perceptron-0.1.0.0/build
    /home/jurydes/.local/lib /usr/lib/x86_64-linux-gnu
    /lib/x86_64-linux-gnu

data-dir:             /home/jurydes/mlp/perceptron/.
hs-libraries:         HSperceptron-0.1.0.0-inplace
depends:
    base-4.18.3.0 directory-1.3.8.5
    hmatrix-0.20.2-abc109a82c819d4aefb876a33279d81dd08912cc9291175af0bd8d5480a7cdb2

haddock-interfaces:
    /home/jurydes/mlp/perceptron/dist-newstyle/build/x86_64-linux/ghc-9.6.7/perceptron-0.1.0.0/doc/html/perceptron/perceptron.haddock

haddock-html:
    /home/jurydes/mlp/perceptron/dist-newstyle/build/x86_64-linux/ghc-9.6.7/perceptron-0.1.0.0/doc/html/perceptron
